[tool.towncrier]
directory = "newsfragment"
filename = "CHANGES.md"
name = "Changes in MyBussines"
# Note: there is a bug, if I use title_format, the title is printed twice
# title_format = "Changes in MyBussines {version} ({project_date})"
template="tools/towncrier/template.md"
